#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libxshmfence
Version  : 1.2
Release  : 3
URL      : http://xorg.freedesktop.org/releases/individual/lib/libxshmfence-1.2.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libxshmfence-1.2.tar.bz2
Summary  : The X Shared Memory Fence Library
Group    : Development/Tools
License  : MIT
Requires: libxshmfence-lib
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
libxshmfence - Shared memory 'SyncFence' synchronization primitive
This library offers a CPU-based synchronization primitive compatible
with the X SyncFence objects that can be shared between processes
using file descriptor passing.

%package dev
Summary: dev components for the libxshmfence package.
Group: Development
Requires: libxshmfence-lib

%description dev
dev components for the libxshmfence package.


%package lib
Summary: lib components for the libxshmfence package.
Group: Libraries

%description lib
lib components for the libxshmfence package.


%prep
%setup -q -n libxshmfence-1.2

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/xshmfence.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
